###############################################################################
## System Logger  https://www.home-assistant.io/components/logger
## levels: debug, fatal, critical, error, warning, warn, info, notset
###############################################################################
default: warn
# logs:
filters:
  pybalboa.balboa:
    - "Spa stopped responding, requesting panel config" #ERROR (MainThread) [pybalboa.balboa] Spa stopped responding, requesting panel config.
    - "Lost connection to spa, attempting reconnect" #ERROR (MainThread) [pybalboa.balboa] Lost connection to spa, attempting reconnect.
    - "Error connecting to spa" #ERROR (MainThread) [pybalboa.balboa] Error connecting to spa at 192.168.1.125:4257: [Errno 110] Connect call failed ('192.168.1.125', 4257)
    - "Connection reset by peer" #ERROR (MainThread) [pybalboa.balboa] Connection reset by peer
    - "Message had bad CRC" #ERROR (MainThread) [pybalboa.balboa] Message had bad CRC, discarding
    - "Spa unreachable" #ERROR (MainThread) [pybalboa.balboa] Spa unreachable
    - "Spa sent an unknown message" #ERROR (MainThread) [pybalboa.balboa] Spa sent an unknown message: 7e17ffaf26008700000002000001000000000000000000087e
    - "Spa read failed" #ERROR (MainThread) [pybalboa.balboa] Spa read failed: 0 bytes read on a total of 2 expected bytes
    - "Error sending message: Connection lost" #ERROR (MainThread) [pybalboa.balboa] Error sending message: Connection lost
  custom_components.balboa.const: # homeassistant.components.balboa.const:
    - "Failed to connect to spa" #ERROR (MainThread) [homeassistant.components.balboa.const] Failed to connect to spa at 192.168.1.125
  homeassistant.components.zwave_js: # manual zwave entity polling
    - "Refreshing primary value" #INFO (MainThread) [homeassistant.components.zwave_js.entity] Refreshing primary value Value(value_id='161-37-0-currentValue') for switch.fireplace, state update may be delayed for devices on battery
  homeassistant.components.automation.zwave_poll_fireplace_switch: # manual zwave entity polling
    - "Running automation actions" #INFO (MainThread) [homeassistant.components.automation.zwave_poll_fireplace_switch] [Zwave] Poll Fireplace Switch: Running automation actions
    - "Executing step call service" #INFO (MainThread) [homeassistant.components.automation.zwave_poll_fireplace_switch] [Zwave] Poll Fireplace Switch: Executing step call service
  # pychromecast.socket_client:
  #   - "Heartbeat timeout, resetting connection" #WARNING (Thread-26) [pychromecast.socket_client] [Laundry Room Speaker(192.168.1.197):8009] Heartbeat timeout, resetting connection
  #   - "Failed to connect to service" #ERROR (Thread-26) [pychromecast.socket_client] [Laundry Room Speaker(192.168.1.197):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.197', 8009)), retrying in 5.0s
  #   - "Error reading from socket" #ERROR (Thread-9) [pychromecast.socket_client] [Bedroom Hub(192.168.1.194):8009] Error reading from socket.
  #   - "Error communicating with socket, resetting connection" #WARNING (Thread-9) [pychromecast.socket_client] [Bedroom Hub(192.168.1.194):8009] Error communicating with socket, resetting connection
  homeassistant.components.roku.coordinator:
    - "Error fetching roku data" #ERROR (MainThread) [homeassistant.components.roku.coordinator] Error fetching roku data: Invalid response from API: Timeout occurred while connecting to device
  homeassistant.helpers.entity:
    - " is taking over 10 seconds" #WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.wan is taking over 10 seconds
  homeassistant.components.proximity:
    - "Jason: proximity calculation complete" #INFO (MainThread) [homeassistant.components.proximity] Jason: proximity calculation complete
  homeassistant.components.sensor:
    - "waqi: Error on device update!" #ERROR (MainThread) [homeassistant.components.sensor] waqi: Error on device update!
  homeassistant.components.mold_indicator.sensor: # triggered when templates are reloaded
    - "Unable to parse temperature sensor sensor.outdoor_temperature with state: unavailable" #ERROR (MainThread) [homeassistant.components.mold_indicator.sensor] Unable to parse temperature sensor sensor.outdoor_temperature with state: unavailable
  homeassistant.components.stream.stream.camera.charlie_crate: # opened in UI when camera off
    - "Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found)" #ERROR (stream_worker) [homeassistant.components.stream.stream.camera.charlie_crate] Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsp://****:****@192.168.1.100:8554/charlie-crate
  homeassistant.components.stream.stream.camera.living_room: # opened in UI when camera off
    - "Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found)" #ERROR (stream_worker) [homeassistant.components.stream.stream.camera.living_room] Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsp://****:****@192.168.1.100:8554/living-room
  homeassistant.components.glances.coordinator: #ISSUE occurs regularly
    - "Error fetching glances - localhost data" #ERROR (MainThread) [homeassistant.components.glances.coordinator] Error fetching glances - localhost data:

  homeassistant.components.media_player: #TEMP try when TV hard wired
    - "longer than the scheduled update interval" #WARNING (MainThread) [homeassistant.components.media_player] Updating webostv media_player took longer than the scheduled update interval
  custom_components.nest_protect: #TEMP until fix
    - 504 error while authenticating" #ERROR (MainThread) [custom_components.nest_protect] 504 error while authenticating - . Please create an issue on GitHub.
    - "Unknown pynest exception" #ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
  custom_components.nest_protect.pynest: #TEMP until fix
    - "Authentication error: invalid_request" #ERROR (MainThread) [custom_components.nest_protect.pynest] Authentication error: invalid_request
    - "Could not interpret Nest response" #ERROR (MainThread) [custom_components.nest_protect.pynest] Could not interpret Nest response
  custom_components.frigate.api: #TEMP until fix
    - "Timeout error fetching information" #ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
  custom_components.frigate: #TEMP until fix
    - "Error fetching frigate data" #ERROR (MainThread) [custom_components.frigate] Error fetching frigate data:
  homeassistant.components.shelly: #TEMP until fix
    - "Error fetching Side Entrance Motion data" #ERROR (MainThread) [homeassistant.components.shelly] Error fetching Side Entrance Motion data: Sleeping device did not update within 3600 seconds interval

