###############################################################################
# System Logger
## https://www.home-assistant.io/components/logger
## - set log to info level here so boot is always logged
## - default log will reset to level selected in UI after boot
## - debug, fatal, critical, error, warning, warn, info, notset
###############################################################################
default: info
logs:
  homeassistant.bootstrap: error
    # WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lutron_caseta
#   homeassistant.core: info
#     # ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
#   homeassistant.loader: info
#     # WARNING (MainThread) [homeassistant.loader] You are using a custom integration for
#   homeassistant.setup: error
#     # INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.0 seconds.
#     # WARNING (MainThread) [homeassistant.setup] Setup of person is taking over 10 seconds.

  homeassistant.helpers.condition: debug
  # homeassistant.helpers.entity: critical
    # WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.jason_home_week is taking over 10 seconds
    # ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.waqi_windsor fails
#   homeassistant.helpers.entity_registry: error
#     # INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new geo_location.gdacs entity: geo_location.drought_hispaniola_2020
#   homeassistant.helpers.restore_state: error
#   homeassistant.helpers.storage: error
#     # DEBUG (SyncWorker_18) [homeassistant.helpers.storage] Writing data for core.restore_state
#   homeassistant.helpers.script: debug
#   homeassistant.helpers.service: debug
#     # WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities automation.schedule_auto_shift_select
#   homeassistant.helpers.translation: info

#   homeassistant.util.json: error
#   homeassistant.util.yaml: error
#   homeassistant.util.yaml.loader: error
#     # DEBUG (SyncWorker_3) [homeassistant.util.yaml.loader] Secret TRAFFIC_MAP_URL retrieved from secrets.yaml in folder /config
#   homeassistant.util.package: error

#   homeassistant.components.alarm_control_panel: error
#   homeassistant.components.alert: error
#     # DEBUG (MainThread) [homeassistant.components.alert] Watched entity (binary_sensor.shift_override) has changed
#     # DEBUG (MainThread) [homeassistant.components.alert] Beginning Alert: Shift Override
#   homeassistant.components.automation: info
#   homeassistant.components.binary_sensor: error
#   homeassistant.components.bluetooth_tracker: error
#   homeassistant.components.calendar: error
#     # WARNING (MainThread) [homeassistant.components.calendar] Setup of calendar platform google is taking over 10 seconds.
#   homeassistant.components.camera: error
#     # WARNING (MainThread) [homeassistant.components.camera] Updating nwsradar camera took longer than the scheduled update interval 0:00:30
#   homeassistant.components.cast: error
#   homeassistant.components.cert_expiry: error
#     # ERROR (MainThread) [homeassistant.components.cert_expiry] Certificate validation error: 192.168.1.110 [self signed certificate]
#   homeassistant.components.climate: error
#   homeassistant.components.cloud: error
#   homeassistant.components.command_line.sensor: error
#   homeassistant.components.counter: error
#   homeassistant.components.cover: error
#     # WARNING (MainThread) [homeassistant.components.cover] Updating myq cover took longer than the scheduled update interval 0:00:15
  # homeassistant.components.device_tracker: error
    # WARNING (MainThread) [homeassistant.components.device_tracker] Updating device list from legacy took longer than the scheduled scan interval 0:02:00
#   homeassistant.components.info: error
#   homeassistant.components.fan: error
#     # WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform template is taking over 10 seconds.
#   homeassistant.components.flux: error
#     # DEBUG (MainThread) [homeassistant.components.flux.switch] Lights updated to x:0.49 y:0.382 brightness:175, 94% of day cycle complete at 2020-03-01 17:39:32.016739-05:00
#   homeassistant.components.gdacs: error
#     # DEBUG (MainThread) [homeassistant.components.gdacs.geo_location] Updating DR1012649
  homeassistant.components.generic.camera: critical
    # ERROR (MainThread) [homeassistant.components.generic.camera] Timeout getting camera image from EC ROW HOWARD
#   homeassistant.components.geo_location: error
#   homeassistant.components.glances: error
#   homeassistant.components.google_assistant: error
#   homeassistant.components.google_maps: error
  # homeassistant.components.google_maps.device_tracker: error
    # WARNING (SyncWorker_11) [homeassistant.components.google_maps.device_tracker] Ignoring Sheri update because timestamp is older than last timestamp
#   homeassistant.components.google_travel_time: error
#     # DEBUG (SyncWorker_6) [homeassistant.components.google_travel_time.sensor] person.jason is in zone.home, getting zone location
#   homeassistant.components.hassio: error
#   homeassistant.components.hassio.handler: debug
#     # ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /discovery request (startup)
#     # ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /homeassistant/restart request (restart)
#     # ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /homeassistant/options request (startup)
#   homeassistant.components.hassio.discovery: debug
#     # ERROR (MainThread) [homeassistant.components.hassio.discovery] Can't read discover info:
#   homeassistant.components.history: error
#   homeassistant.components.homekit_controller: error
#     # DEBUG (MainThread) [homeassistant.components.homekit_controller.config_flow] Discovered device Smart Bridge 2 (Smart Bridge 2 - 28:60:cd:cf:f5:fc)
#  homeassistant.components.http: debug
#  homeassistant.components.http.auth: debug
#     # DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 172.30.32.2 for /api/config using bearer token
  # homeassistant.components.http.ban: debug
#     # WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 129.9.75.195
#  homeassistant.components.http.view: debug
#     # DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/webhook/eb9270ca6d2867abd9b53710a777bfd7733f08b4552079ea5bce75d44a638a3e to 192.168.1.172 (auth: False)
#   homeassistant.components.hydrawise: error
#   homeassistant.components.input_boolean: error
#   homeassistant.components.input_datetime: error
#   homeassistant.components.input_number: error
#   homeassistant.components.input_select: error
#   homeassistant.components.iqvia: error
#   homeassistant.components.light: error
#     # WARNING (MainThread) [homeassistant.components.light] Setup of light platform group is taking over 10 seconds.
#   homeassistant.components.lock: error
#     # WARNING (MainThread) [homeassistant.components.lock] Setup of lock platform zwave is taking over 10 seconds.
#   homeassistant.components.logbook: error
#     # DEBUG (SyncWorker_11) [homeassistant.components.logbook] fetching 49 distinct domain/entity_id pairs took 0.038824s
#   homeassistant.components.lutron_caseta: error
#   homeassistant.components.media_player: error
#     # WARNING (MainThread) [homeassistant.components.media_player] Updating spotify media_player took longer than the scheduled update interval 0:00:30
#   homeassistant.components.mobile_app: error
#   homeassistant.components.mobile_app.notify: warn
#     # INFO (MainThread) [homeassistant.components.mobile_app.notify] mobile_app push notification rate limits for jphone: 53 sent, 300 allowed, 0 errors, resets in 7:54:02
#   homeassistant.components.mobile_app.webhook: error
#   homeassistant.components.mold_indicator: error
#   homeassistant.components.mqtt: error
#   homeassistant.components.myq: error
#   homeassistant.components.nest: error
#   homeassistant.components.nmap_tracker: error
#     # WARNING (MainThread) [homeassistant.components.device_tracker] Updating device list from legacy took longer than the scheduled scan interval 0:00:12
#   homeassistant.components.notify: error
  homeassistant.components.onvif: critical
    # ERROR (MainThread) [homeassistant.components.onvif] Fetch snapshot image failed from Lorex NVR, falling back to FFmpeg; Unknown error: Failed to authenticate to http://192.168.1.100/onvifsnapshot/media_service/snapshot?channel=2&subtype=1
#   homeassistant.components.openuv: error
#   homeassistant.components.person: error
#   homeassistant.components.ping: error
#   homeassistant.components.proximity: error  warn # constant updates
#   homeassistant.components.recorder: error
  homeassistant.components.rest.sensor: error
    # WARNING (MainThread) [homeassistant.components.rest.sensor] JSON result was not a dictionary or list with 0th element a dictionary
#   homeassistant.components.scene: error
#   homeassistant.components.season: error
#   homeassistant.components.sensor: error
#     # WARNING (MainThread) [homeassistant.components.sensor] Setup of platform sensor is taking over 10 seconds.
#   homeassistant.components.shell_command: error
#   homeassistant.components.smtp: debug
#   homeassistant.components.speedtestdotnet: error
#   homeassistant.components.sql: error
#   homeassistant.components.ssdp: error
#     # DEBUG (MainThread) [homeassistant.components.ssdp] Error fetching http://192.168.1.130:49152/upnp_device_desc.xml:
#   homeassistant.components.statistics: error
#     # DEBUG (MainThread) [homeassistant.components.statistics.sensor] sensor.indoor_temperature_stats: updating statistics.
#     # DEBUG (MainThread) [homeassistant.components.statistics.sensor] sensor.indoor_temperature_stats: purging records older then 2020-02-06 04:07:17.655094-05:00(30 days, 0:00:00)
#     # DEBUG (MainThread) [homeassistant.components.statistics.sensor] sensor.indoor_temperature_stats: scheduling update at 2020-03-26 22:09:14+00:00
#   homeassistant.components.sun: error
#   homeassistant.components.system_log: error
#   homeassistant.components.system_log.external: debug  # leave on debug so all custom log entries always display
#   homeassistant.components.switch: error
#     # WARNING (MainThread) [homeassistant.components.switch] Setup of platform switch is taking over 10 seconds.
#   homeassistant.components.template: error
#   homeassistant.components.template.light: error
#     # ERROR (MainThread) [homeassistant.components.template.light] Received invalid light is_on state: unavailable. Expected: on, off, true, false
#   homeassistant.components.timer: error
#   homeassistant.components.unifi_direct: error
#   homeassistant.components.unifi_direct.device_tracker: error
#   homeassistant.components.updater: error  # no need to see updates
  # homeassistant.components.upnp: critical
    # ERROR (MainThread) [homeassistant.components.upnp] Timeout fetching J-ROUTER data
#   homeassistant.components.uptime: error
#   homeassistant.components.utility_meter: error
#   homeassistant.components.waqi: critical  # error on every failed update
#   homeassistant.components.webhook: error
#     # DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for 56086961440f8e553082603c0ad229dd87b4246bab27115940230b93c169f388
#     # ERROR (MainThread) [homeassistant.components.webhook] Error processing webhook 56086961440f8e553082603c0ad229dd87b4246bab27115940230b93c169f388
#   homeassistant.components.websocket_api: info
#   homeassistant.components.websocket_api.http.connection: info
#     # ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1809016464] Client exceeded max pending messages [2]: 512
#   homeassistant.components.workday: error
#   homeassistant.components.zeroconf: error
#   homeassistant.components.zone: error
#     # WARNING (MainThread) [homeassistant.components.zone] Updating zone zone took longer than the scheduled update interval 0:00:15
#   homeassistant.components.zone_storage_collection: error
#   homeassistant.components.zwave: error
#   homeassistant.components.zwave.util: error

  # custom_components.authenticated: info
  # custom_components.sensor.authenticated: debug
#   custom_components.breaking_changes: error
#   custom_components.bwalarm: error
  # custom_components.climacell.sensor: error
#   custom_components.composite: error
#   custom_components.illuminance: error
  # custom_components.nwsradar: critical
    # ERROR (MainThread) [custom_components.nwsradar] Timeout fetching DTX Enhanced Composite Reflectivity Loop data
#   custom_components.spotcast: error
#  custom_components.spotcast.sensor: critical
#     #NIKLAS: <class 'pychromecast.Chromecast'> DeviceStatus(friendly_name='Bedroom display', model_name='Google Nest Hub', manufacturer='Google Inc.', uuid=UUID('85f11cb6-c3c9-53c1-dd58-

#   aiocache: debug
#   aiocache.base: debug
#   aio_georss_client: error
#     # DEBUG (MainThread) [aio_georss_client.feed_manager] New entity added DR1012806
#   aio_georss_client.feed: error
#     # WARNING (MainThread) [aio_georss_client.feed] Requesting data from https://www.gdacs.org/xml/rss.xml failed with timeout error
#   aio_georss_client.feed_manager: error
#     # WARNING (MainThread) [aio_georss_client.feed_manager] Update not successful, no data received from <GdacsFeed(home=(42.304220273354154, -82.92540550034799), url=https://www.gdacs.org/xml/rss.xml, radius=4023.36, categories=[])>
#   AIOGitHubAPI: error
#   aiohttp.server: debug
#     # DEBUG (MainThread) [aiohttp.server] Socket error
#   aiohttp.websocket: debug
#     # WARNING (MainThread) [aiohttp.websocket] websocket connection is closing.
#   backoff: debug
#   botocore: error   # polly
#   frontend: critical
#     # ERROR (MainThread) [frontend.js.latest.202007160] https://jazzyisj.duckdns.org/hacsfiles/lovelace-swipe-navigation/swipe-navigation.js:10:21 Uncaught TypeError: Cannot read property 'lovelace' of null
#   github.Requester: error
#   glances_api: error
  # googleapiclient.discovery: warn # google calendar
#   google.auth.transport.requests: info
#   hacs: error
#   libopenzwave: error
#   locationsharinglib: error
#   nest: error
#   oauth2client.client: info
#   oauth2client.transport: info
#   openzwave: error
#   PIL.Image: error
#   PIL.PngImagePlugin: error
  pybalboa.balboa: critical
#   pyhaversion: error
#   pymyq: error
#   pymyq.api: error
#   pyupdate: error
  # pychromecast: error
    # INFO (SyncWorker_1) [pychromecast] Querying device status - every 30 seconds
  # pychromecast.controllers: error
#   pychromecast: error   warn
#
  # pychromecast.socket_client: critical
#     # ERROR (Thread-109) [pychromecast.socket_client] [Music Speakers(192.168.1.171):42682] Failed to connect to service Google-Cast-Group-036b79b7e7b84e9585e1ad9504c93635._googlecast._tcp.local., retrying in 5.0s
      # ERROR (Thread-11) [pychromecast.socket_client] [Bedroom TV(192.168.1.161):8009] Error reading from socket.
#   pylutron_caseta: error
#   root: debug
#   sseclient: info
#     # DEBUG (Thread-5) [sseclient] Dispatching keep-alive event, 4 bytes...
#   spotipy.client: error
#   hass_nabucasa: error
#   hass_nabucasa.cloud_api: error
#   hass_nabucasa.iot: error
#   hass_nabucasa.google_report_state: error
#     # INFO (MainThread) [hass_nabucasa.google_report_state] Connection closed
#   hass_nabucasa.remote: error
#     # DEBUG (MainThread) [hass_nabucasa.remote] Retrieve instance data: {'status': 200, 'domain': '82l1mjsgl3dp23jw4nd1sh0n7ykww05d.ui.nabu.casa', 'email': 'hassio.jazzyisj@gmail.com', 'server': 'us-east-1.ui.nabu.casa'}
#   snitun.utils.aiohttp_client: error
#   snitun.multiplexer.core: error
#   snitun.client.connector: error
#   snitun.multiplexer.channel: error
#   zeroconf: error
